# Generated by Django 2.0.2 on 2018-02-25 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musical_title', models.TextField()),
                ('playwright', models.TextField()),
                ('composer', models.TextField()),
                ('lyricist', models.TextField(blank=True)),
                ('genre', models.TextField(blank=True)),
                ('production_year', models.TextField(blank=True)),
                ('plot', models.TextField()),
                ('pendingNon', models.CharField(max_length=12)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField()),
                ('pendingNon', models.CharField(max_length=12)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('musical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Musical')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.TextField()),
                ('singer', models.TextField()),
                ('artist', models.TextField()),
                ('genre', models.TextField(blank=True)),
                ('original_musical', models.TextField(blank=True)),
                ('musicalNon', models.CharField(max_length=12)),
                ('sheet_music', models.URLField(blank=True)),
                ('spotify_id', models.TextField(blank=True)),
                ('spotify_preview', models.URLField(blank=True)),
                ('pendingNon', models.CharField(max_length=12)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('user_email', models.EmailField(max_length=254)),
                ('password', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application.User'),
        ),
        migrations.AddField(
            model_name='role',
            name='song',
            field=models.ManyToManyField(to='application.Song'),
        ),
        migrations.AddField(
            model_name='role',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application.User'),
        ),
        migrations.AddField(
            model_name='musical',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application.User'),
        ),
    ]
